#:import mod bin.views.modules
#:import img bin.constants

<MenuSub>
    ScrollView:
        do_scroll_x: False
        do_scroll_y: True
        GridLayout:
            id: menu
            cols: 1
            size_hint_y: None
            height: self.minimum_height
            Button:
                text: 'Recording'
                bold: True
                size_hint_y: None
                height: 40
                on_press: app.screen_manager.current = "OBSView"
            Button:
                text: 'ThumbnailGenerate'
                bold: True
                size_hint_y: None
                height: 40
                on_press: app.screen_manager.current = "ThumbnailGenerateView"
            Button:
                text: 'FetchAudio'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'FixAudio'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'Send2Audacity'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'CompAndRender'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'SetTitle'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'Deploy'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'TadEditor'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'FileManager'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'Settings'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'About'
                bold: True
                size_hint_y: None
                height: 40

<OBSView>
    
    #* Select Lets Play
    #* Connect to OBS Button
    #* Connection Information
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        MenuSub: 

<ThumbnailGenerateView>
    
    #* Select Lets Play
    #* Connect to OBS Button
    #* Connection Information
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        MenuSub: 

<WelcomeView>
    #center: {"center_x": 0.5, "center_y": 0.5}
    FloatLayout:
        pos_hint:  {"center_x": 0.5, "center_y": 0.5}
        size_hint: (1.0, 1.0)
        Image:
            texture: mod.b64toki(img.IMG_WELCOME)
            fit_mode: 'cover'
            pos_hint:  {"center_x": 0.5, "center_y": 0.5}
        Image:
            texture: mod.b64toki(img.IMG_LOGO)
            size_hint: (0.3, 0.3)
            pos_hint: {"center_x": 0.5, "center_y": 0.8}
        Label:
            text: img.DISCLAIMER
        Button:
            text: 'Los gehts'
            bold: True
            background_color: '#33cccc'
            background_normal: ''
            size_hint: (0.2, 0.1)
            pos_hint: {"center_x": 0.5, "center_y": 0.3}
            on_press: app.screen_manager.current = 'OBSView'


<MainWidget>
    screen_manager: screen_manager
    
    ScreenManager:
        id: screen_manager
        Screen:
            name: "WelcomeView"
            WelcomeView:
                manager: screen_manager
        Screen:
            name: "OBSView"
            OBSView:
                manager: screen_manager
        Screen:
            name: "ThumbnailGenerateView"
            OBSView:
                manager: screen_manager


