#:import module module.main
<DropDownSelector>:
    id: episode_start
    # Diese Buttons werden automatisch unter dem Label aus main.kv eingefügt
    Button:
        text: "Extension Button A"
        size_hint_y: None
        height: 44
        on_press: print("A gedrückt")

    Button:
        text: "Extension Button B"
        size_hint_y: None
        height: 44
        on_press: module.overwrite(episode_start)

<MenuSub>
    ScrollView:
        do_scroll_x: False
        do_scroll_y: True
        GridLayout:
            id: menu
            cols: 1
            size_hint_y: None
            height: self.minimum_height
            Button:
                text: 'Recording'
                bold: True
                size_hint_y: None
                height: 40
                on_press: app.screen_manager.current = "OBSView"
            Button:
                text: 'ThumbnailGenerate'
                bold: True
                size_hint_y: None
                height: 40
                on_press: app.screen_manager.current = "ThumbnailGenerateView"
            Button:
                text: 'FetchAudio'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'FixAudio'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'Send2Audacity'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'CompAndRender'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'SetTitle'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'Deploy'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'TadEditor'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'FileManager'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'Settings'
                bold: True
                size_hint_y: None
                height: 40
            Button:
                text: 'About'
                bold: True
                size_hint_y: None
                height: 40


<OBSView>
    id: obs
    #* Select Lets Play
    #* Connect to OBS Button
    #* Connection Information
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        GridLayout:
            cols: 1
            LPEPSub: 
                run_callback: obs.toggle_watching_state
            Label:
                id: timer
                text: 'OBS is not connected yet'
                size_hint_y: None
                height: 40
            DropDownSelector:

                

<ThumbnailGenerateView>
    
    #* Select Lets Play
    #* Select Episode Range
    #* Run
    #* Check Each
    #* Preview
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        LPEPSub: 


<FetchAudioView>
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        LPEPSub: 

<FixAudioView>
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        LPEPSub: 

<Send2AudacityView>
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        LPEPSub: 
    
<CompAndRenderView>
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        LPEPSub: 

<SetTitleView>
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        LPEPSub: 

<DeployView>
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        LPEPSub: 

<TadEditorView>
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        LPEPSub: 
    
<FileManagerView>
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        LPEPSub: 

<SettingsView>
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        LPEPSub: 

<AboutView>
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        LPEPSub: 