<OBSView>
    
    #* Select Lets Play
    #* Connect to OBS Button
    #* Connection Information
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        MenuSub: 

<ThumbnailGenerateView>
    
    #* Select Lets Play
    #* Select Episode Range
    #* Run
    #* Check Each
    #* Preview
    GridLayout:
        cols: 2
        size_hint: (1.0, 1.0) 
        MenuSub:
            size_hint: (0.3, 1.0) 
        MenuSub: 
