#:import mod src.api.b642img
#:import img src.api.icons
#:import con src.api.constants

<LPEPSub>
    GridLayout:
        cols: 1
        BoxLayout:
            Label:
                text: "Lets Play"
            DropDown:
            Label:
                text: "Episode start"
            DropDown:
            Label:
                text: "Episode end"
            Button:
                text: "Run"

<Preview>
    Switch:
        text: "Check Each"
    Image:

<WelcomeView>
    #center: {"center_x": 0.5, "center_y": 0.5}
    FloatLayout:
        pos_hint:  {"center_x": 0.5, "center_y": 0.5}
        size_hint: (1.0, 1.0)
        Image:
            texture: mod.b64toki(img.IMG_WELCOME)
            fit_mode: 'cover'
            pos_hint:  {"center_x": 0.5, "center_y": 0.5}
        Image:
            texture: mod.b64toki(img.IMG_LOGO)
            size_hint: (0.3, 0.3)
            pos_hint: {"center_x": 0.5, "center_y": 0.8}
        Label:
            text: con.DISCLAIMER
        Button:
            text: 'Los gehts'
            bold: True
            background_color: '#33cccc'
            background_normal: ''
            size_hint: (0.2, 0.1)
            pos_hint: {"center_x": 0.5, "center_y": 0.3}
            on_press: app.screen_manager.current = 'OBSView'

<MainWidget>
    screen_manager: screen_manager 
    ScreenManager:
        id: screen_manager
        Screen:
            name: "WelcomeView"
            WelcomeView:
                manager: screen_manager
        Screen:
            name: "OBSView"
            OBSView:
                manager: screen_manager
        Screen:
            name: "ThumbnailGenerateView"
            OBSView:
                manager: screen_manager